name: "Unit Tests"

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '23' 
      - run: npm install
      - name: Run Tests
        run: npm test
